-- Create posts table
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text,
  excerpt text,
  image text,
  published_at date default CURRENT_DATE
);

-- Set up Row Level Security (RLS)
alter table public.posts enable row level security;

-- Policy: Allow public read access
create policy "Public posts are viewable by everyone"
  on public.posts for select
  using ( true );

-- Policy: Allow authenticated users (admins) to insert
create policy "Admins can insert posts"
  on public.posts for insert
  with check ( auth.role() = 'authenticated' );

-- Policy: Allow authenticated users (admins) to update
create policy "Admins can update posts"
  on public.posts for update
  using ( auth.role() = 'authenticated' );

-- Policy: Allow authenticated users (admins) to delete
create policy "Admins can delete posts"
  on public.posts for delete
  using ( auth.role() = 'authenticated' );
