-- Create properties table
create table public.properties (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  price numeric,
  bedrooms numeric,
  bathrooms numeric,
  area numeric,
  plot numeric,
  image text,
  type text,
  city text,
  province text,
  latitude numeric,
  longitude numeric,
  features text[]
);

-- Create leads table
create table public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text,
  message text,
  status text default 'New',
  source text,
  property_id bigint references public.properties(id),
  property_title text
);

-- Enable Row Level Security (RLS)
alter table public.properties enable row level security;
alter table public.leads enable row level security;

-- Create policies
-- Allow public read access to properties
create policy "Public properties are viewable by everyone"
  on public.properties for select
  using ( true );

-- Allow authenticated users (admin) to insert/update/delete properties
-- For simplicity in this demo, we might allow anon insert if auth isn't fully set up, 
-- but ideally this should be authenticated only.
-- Assuming the admin login uses Supabase Auth, we can use:
create policy "Authenticated users can modify properties"
  on public.properties for all
  using ( auth.role() = 'authenticated' );

-- Allow public to insert leads (contact form)
create policy "Public can insert leads"
  on public.leads for insert
  with check ( true );

-- Allow authenticated users (admin) to view/modify leads
create policy "Authenticated users can view leads"
  on public.leads for select
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can update leads"
  on public.leads for update
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can delete leads"
  on public.leads for delete
  using ( auth.role() = 'authenticated' );
