-- Create property_media table
create table public.property_media (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  property_id bigint references public.properties(id) on delete cascade not null,
  url text not null,
  type text not null check (type in ('image', 'plan', 'video')),
  title text
);

-- Enable Row Level Security (RLS)
alter table public.property_media enable row level security;

-- Create policies
-- Allow public read access to media
create policy "Public media are viewable by everyone"
  on public.property_media for select
  using ( true );

-- Allow authenticated users (admin) to insert media
create policy "Authenticated users can insert media"
  on public.property_media for insert
  with check ( auth.role() = 'authenticated' );

-- Allow authenticated users (admin) to delete media
create policy "Authenticated users can delete media"
  on public.property_media for delete
  using ( auth.role() = 'authenticated' );
